### ISSUE TITLE
suggestion: add agon-light topic

### ISSUE THREAD

**Issue by andypiper** [LuzrBum/Agon-OregonTrail#1]
Could you add the [agon-light](https://github.com/topics/agon-light) GitHub topic to this repo, to aid in community discovery of related resources? Thanks! 🙏🏻

**Comment by alephnull42** [comment]
Resolved - added topic agon-light for all agon repos - thank you very much for the suggestion!

**Comment by andypiper** [comment]
nice, thanks!
